server.port: @server.port@

sources:
  cbr:
    initialTime: "2016-12-31T21:00:00Z"
    provider:
      url: http://www.cbr.ru/scripts/XML_daily.asp
      timezone: Europe/Moscow
    cron:
      value: "00 21 * * *"
      timezone: Europe/Moscow
      delayMs: 0

