server.port: @server.port@
spring.application.name: @project.name@

management:
  security:
    flag: false
  server:
    port: '@management.port@'
  metrics:
    export:
      statsd:
        flavor: etsy
        enabled: false
      prometheus:
        enabled: false
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus


service:
  mg:
    automaton:
      url: http://machinegun:8022/v1/automaton
      namespace: xrates
    eventSink:
      url: http://localhost:8022/v1/event_sink
      sinkId: xrates
    networkTimeout: 5000
sources:
  needInitialize: true
  cbr:
    sourceId: "CBR"
    initialTime: "2015-12-31T21:00:00Z"
    provider:
      url: https://www.cbr.ru/scripts/XML_daily.asp
      timezone: Europe/Moscow
    cron:
      value: "00 21 * * *"
      timezone: Europe/Moscow
      delay: PT3H
  psb-mastercard:
    sourceId: "PSB-MASTERCARD"
    initialTime: "2020-02-17T21:00:00Z"
    provider:
      terminalId:
      secretKey:
      paymentSystem: MASTERCARD
      url: https://3ds.payment.ru/cgi-bin/curr_rate_by_date
      timezone: Europe/Moscow
    cron:
      value: "00 01 * * *"
      timezone: Europe/Moscow
      delay: PT-1H
  psb-visa:
    sourceId: "PSB-VISA"
    initialTime: "2020-02-17T21:00:00Z"
    provider:
      terminalId:
      secretKey:
      paymentSystem: VISA
      url: https://3ds.payment.ru/cgi-bin/curr_rate_by_date
      timezone: Europe/Moscow
    cron:
      value: "00 01 * * *"
      timezone: Europe/Moscow
      delay: PT-1H
