server.port: @server.port@
spring.application.name: @project.name@
management.metrics.export.statsd.flavor: etsy
service:
  mg:
    automaton:
      url: http://machinegun:8022/v1/automaton
      namespace: rates
    eventSink:
      url: http://localhost:8022/v1/event_sink
      sinkId: rates
    networkTimeout: 5000
sources:
  needInitialize: true
  cbr:
    initialTime: "2016-12-31T21:00:00Z"
    provider:
      url: http://www.cbr.ru/scripts/XML_daily.asp
      timezone: Europe/Moscow
    cron:
      value: "00 21 * * *"
      timezone: Europe/Moscow
      delayMs: 10800000 # 3 hours

