server.port: @server.port@
service:
  mg:
    url: http://machinegun:8022/v1/automaton
    networkTimeout: 5000
    namespace: rates
sources:
  needInitialize: true
  cbr:
    initialTime: "2016-12-31T21:00:00Z"
    provider:
      url: http://www.cbr.ru/scripts/XML_daily.asp
      timezone: Europe/Moscow
    cron:
      value: "00 21 * * *"
      timezone: Europe/Moscow
      delayMs: 10800000 # 3 hours

